/* eslint-disable */

declare module 'glob:./sources/{*.ts,**/index.ts}' {
  export const _36kr: typeof import('./sources/_36kr')
  export const baidu: typeof import('./sources/baidu')
  export const bbc: typeof import('./sources/bbc')
  export const bbc_zh: typeof import('./sources/bbc_zh')
  export const bilibili: typeof import('./sources/bilibili')
  export const cankaoxiaoxi: typeof import('./sources/cankaoxiaoxi')
  export const cls: typeof import('./sources/cls/index')
  export const douyin: typeof import('./sources/douyin')
  export const fastbull: typeof import('./sources/fastbull')
  export const gelonghui: typeof import('./sources/gelonghui')
  export const ghxi: typeof import('./sources/ghxi')
  export const github: typeof import('./sources/github')
  export const guardian: typeof import('./sources/guardian')
  export const hackernews: typeof import('./sources/hackernews')
  export const jin10: typeof import('./sources/jin10')
  export const kuaishou: typeof import('./sources/kuaishou')
  export const nytimes_zh: typeof import('./sources/nytimes_zh')
  export const pcbeta: typeof import('./sources/pcbeta')
  export const people_daily: typeof import('./sources/people_daily')
  export const producthunt: typeof import('./sources/producthunt')
  export const thepaper: typeof import('./sources/thepaper')
  export const toutiao: typeof import('./sources/toutiao')
  export const v2ex: typeof import('./sources/v2ex')
  export const wallstreetcn: typeof import('./sources/wallstreetcn')
  export const weibo: typeof import('./sources/weibo')
  export const xueqiu: typeof import('./sources/xueqiu')
  export const zaobao: typeof import('./sources/zaobao')
  export const zhihu: typeof import('./sources/zhihu')
}
